spring:
  application:
    name: challenger-api
  main:
    web-application-type: reactive

server:
  port: 8080

reactor:
  netty:
    worker-count: 16  # Número de hilos del event loop (por defecto = núcleos disponibles)

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,health,info,metrics,httptrace'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

